ollama:
  url: "http://ollama:11434"
  encoder: 
    model: "embeddinggemma:300m"
    window: 768
  llm:
    model: "mistral-nemo:12b-instruct-2407-q4_0"

qdrant:
  url: "http://qdrant:6333"

logs:
  path: "/logs"