ollama:
  url: "http://ollama:11434"
  encoder: 
    model: "bge-m3:567m-fp16"
    window: 8192
  llm:
    model: "mistral-nemo:12b-instruct-2407-q4_0"

qdrant:
  url: "http://qdrant:6333"

logs:
  path: "/logs"