ollama:
  url: "http://ollama:11434"
  llm:
    model: "mistral-nemo:12b-instruct-2407-q4_0"

encoding:
  url: "http://encoding:6999"

qdrant:
  url: "http://qdrant:6333"

logs:
  path: "/logs"