apiVersion: apps/v1
kind: Deployment
metadata:
  name: notebook
  labels:
    app: notebook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notebook
  template:
    metadata:
      labels:
        app: notebook
    spec:
      containers:
        - name: notebook
          image: poke-notebook:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8888
          volumeMounts:
            - name: notebook-storage
              mountPath: /notebook
      volumes:
        - name: notebook-storage
          persistentVolumeClaim:
            claimName: notebook-pvc

