apiVersion: v1
kind: Service
metadata:
  name: notebook
  labels:
    app: notebook
spec:
  type: NodePort
  selector:
    app: notebook
  ports:
    - port: 8888
      targetPort: 8888
      protocol: TCP