apiVersion: apps/v1
kind: Deployment
metadata:
  name: encoding
  labels:
    app: encoding
spec:
  replicas: 1
  selector:
    matchLabels:
      app: encoding
  template:
    metadata:
      labels:
        app: encoding
    spec:
      containers:
        - name: encoding
          image: poke-encoding:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 6999
          volumeMounts:
            - name: encoding-storage
              mountPath: /cache
              mountPropagation: HostToContainer
      volumes:
        - name: encoding-storage
          persistentVolumeClaim:
            claimName: encoding-pvc

