apiVersion: v1
kind: Service
metadata:
  name: encoding
  labels:
    app: encoding
spec:
  type: NodePort
  selector:
    app: encoding
  ports:
    - port: 6999
      targetPort: 6999
      protocol: TCP