embedding:
  model: "Qwen/Qwen3-Embedding-0.6B"

reranker:
  model: "Qwen/Qwen3-Reranker-0.6B"
  max_length: 8192
  padding_side: "left"
  prefix: "<|im_start|>system\nJudge whether the Document meets the requirements based on the Query and the Instruct provided. Note that the answer can only be \"yes\" or \"no\".<|im_end|>\n<|im_start|>user\n"
  suffix: "<|im_end|>\n<|im_start|>assistant\n<think>\n\n</think>\n\n"

cache: "/cache"
